apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: backend
  name: backend-service
spec:
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: backend
status:
  loadBalancer: {}